'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,House,Sprout,ArrowRight,Volume2,ChevronRight,ChevronLeft,Check,X,Bookmark,Users,Cloud,CloudOff,RefreshCw,Download,Search,Eye,Lightbulb,Leaf,Menu} from 'lucide-react';
import {mergeEvents,wordState,wasRecentlyHelped} from './progress.mjs';
import {buildCustomWords} from './custom-word.mjs';
type Evt={id:string;wordId:string;kind:string;at:number;payload:any};
type Question={id:string;kind:string;prompt:string;options:string[];answer:number;explanation:string};
type Word={id:string;term:string;pinyin:string;meaning:string;example:string;confusion:string;oralPrompt:string;questions:Question[];lesson?:any};
type Task={word:Word;question?:Question;options?:{text:string;index:number}[]};
const nav=[{id:'home',title:'今日学习',icon:House},{id:'book',title:'我的课本',icon:BookOpen},{id:'words',title:'字词花园',icon:Sprout},{id:'parent',title:'家长查看',icon:Users}];
const cn=['一','二','三','四','五','六','七','八'];
const unitThemes=['走进自然','学会提问','细心观察','神话之旅','把事情写清楚','童年的故事','心中的家国','故事里的智慧'];
function shuffle<T,>(arr:T[]):T[]{return arr.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.x);}
function dateLabel(at:number){return new Date(at).toLocaleDateString('zh-CN',{month:'long',day:'numeric'});}
function Landscape(){return <svg className="landscape" viewBox="0 0 420 310" role="img" aria-label="翻开的书本化作青绿色山丘，一颗幼苗正在生长"><defs><linearGradient id="hill" x2="0" y2="1"><stop stopColor="#9eb8a5"/><stop offset="1" stopColor="#d8e2c8"/></linearGradient></defs><circle cx="307" cy="75" r="31" fill="#dfb56e"/><path d="M40 227Q110 79 186 153Q236 30 337 171L402 252H30Z" fill="#cddac5"/><path d="M67 253Q152 98 247 178Q299 107 386 256Z" fill="url(#hill)"/><path d="M28 231Q112 210 205 256Q290 213 392 231L365 278Q270 266 205 292Q122 268 57 278Z" fill="#284d43"/><path d="M42 219Q127 203 205 246Q285 200 380 218L365 266Q278 251 205 279Q137 250 58 268Z" fill="#fffdf2"/><path d="M205 246V279M72 240Q139 228 187 258M225 259Q282 232 355 237" fill="none" stroke="#c3cdbb" strokeWidth="2"/><path d="M214 223Q216 169 237 137" fill="none" stroke="#3c6650" strokeWidth="5" strokeLinecap="round"/><path d="M224 183Q178 182 183 147Q222 145 224 183M231 159Q230 124 265 117Q276 153 231 159" fill="#547d58"/><path d="M74 116l6-12m-1 18 10-4M338 195l11-2" stroke="#b29362" strokeWidth="2" strokeLinecap="round"/><circle cx="133" cy="105" r="4" fill="#d2b277"/><path d="M287 43q9-8 17 0q9-8 17 0" fill="none" stroke="#739184" strokeWidth="2"/></svg>;}
export default function LearningApp({userId}:{userId:string|null}) {
  const [data,setData]=useState<any>(null),[dataError,setDataError]=useState(false),[page,setPage]=useState('home');
  const [events,setEvents]=useState<Evt[]>([]),eventRef=useRef<Evt[]>([]),pending=useRef<Evt[]>([]),syncing=useRef(false);
  const [syncStatus,setSyncStatus]=useState('正在读取记录'),[notice,setNotice]=useState(''),[ready,setReady]=useState(false);
  const [activeUnit,setActiveUnit]=useState(1),[search,setSearch]=useState(''),[filter,setFilter]=useState('全部');
  const [study,setStudy]=useState<Word|null>(null),[showPy,setShowPy]=useState(false),[parentWord,setParentWord]=useState<Word|null>(null),[oral,setOral]=useState('');
  const [addingWord,setAddingWord]=useState(false),[customForm,setCustomForm]=useState({term:'',pinyin:'',meaning:'',example:''});
  const [tasks,setTasks]=useState<Task[]>([]),[step,setStep]=useState(0),[feedback,setFeedback]=useState<any>(null),[hint,setHint]=useState(false),[revealed,setRevealed]=useState(false),[confidence,setConfidence]=useState('不确定'),[sessionTitle,setSessionTitle]=useState(''),[completed,setCompleted]=useState<any>(null),[mobileMenu,setMobileMenu]=useState(false);
  const results=useRef<any[]>([]),voiceRef=useRef<SpeechSynthesisUtterance|null>(null);
  const audioRef=useRef<HTMLAudioElement|null>(null),[audioMap,setAudioMap]=useState<Record<string,string>>({});
  const storageKey='ziyouyisi-v1-'+(userId??'local-guest');
  function persist(all:Evt[],queue:Evt[]){try{localStorage.setItem(storageKey,JSON.stringify({events:all,pending:queue}));}catch{setNotice('本机储存空间不足，请保持联网并导出备份。');}}
  async function sync(){
    if(syncing.current)return;
    if(!userId){setSyncStatus('本机体验 · 尚未登录');return;}
    syncing.current=true;setSyncStatus('正在同步');
    try{
      while(pending.current.length){const batch=pending.current.slice(0,40);const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:batch})});if(!r.ok)throw Error();const {accepted}=await r.json() as {accepted:string[]};const ids=new Set(accepted);pending.current=pending.current.filter(e=>!ids.has(e.id));persist(eventRef.current,pending.current);}
      const r=await fetch('/api/progress',{cache:'no-store'});if(!r.ok)throw Error();const remote=await r.json() as {events:Evt[]};const merged=mergeEvents(eventRef.current,remote.events);eventRef.current=merged;setEvents(merged);persist(merged,pending.current);setSyncStatus(pending.current.length?'等待同步':'已保存到云端');
    }catch{setSyncStatus('已存本机 · 等待联网同步');}finally{syncing.current=false;}
  }
  useEffect(()=>{
    fetch('/audio-manifest.json').then(r=>r.ok?r.json():{}).then(m=>setAudioMap(m as Record<string,string>)).catch(()=>{});
    fetch('/curriculum.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(()=>setDataError(true));
    try{const cached=JSON.parse(localStorage.getItem(storageKey)||'{}');if(Array.isArray(cached.events)){eventRef.current=cached.events;setEvents(cached.events);pending.current=Array.isArray(cached.pending)?cached.pending:[];}}catch{setNotice('本机记录读取失败，正在尝试从云端恢复。');}
    setReady(true);sync();const timer=setInterval(sync,30000);window.addEventListener('online',sync);window.addEventListener('focus',sync);return()=>{clearInterval(timer);window.removeEventListener('online',sync);window.removeEventListener('focus',sync);};
  },[userId]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{if(!study&&!parentWord)return;const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){setStudy(null);setParentWord(null);}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[study,parentWord]);
  function add(kind:string,wordId:string,payload:any){const e={id:crypto.randomUUID(),wordId,kind,at:Date.now(),payload};const merged=mergeEvents(eventRef.current,[e]);eventRef.current=merged;pending.current.push(e);setEvents(merged);persist(merged,pending.current);setSyncStatus(userId?'等待同步':'本机体验 · 尚未登录');setTimeout(sync,150);return e;}
  function speak(text:string){audioRef.current?.pause();if('speechSynthesis'in window)speechSynthesis.cancel();if(audioMap[text]&&audioRef.current){audioRef.current.src=audioMap[text];audioRef.current.play().catch(()=>setNotice('音频暂时无法播放，请检查网络后再点一次。'));return;}if(!('speechSynthesis'in window)){setNotice('此浏览器不能朗读，请换用支持普通话朗读的浏览器。');return;}const voices=speechSynthesis.getVoices();const voice=voices.find(v=>/zh[-_]CN/i.test(v.lang))??voices.find(v=>/^zh/i.test(v.lang));if(voices.length&&!voice){setNotice('设备尚未安装中文语音，可先看拼音，或在系统中添加普通话语音。');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=.82;if(voice)u.voice=voice;u.onerror=e=>{if(e.error!=='interrupted'&&e.error!=='canceled')setNotice('朗读暂时不可用，请检查设备中文语音设置。');};voiceRef.current=u;speechSynthesis.speak(u);}
  const lessons=data?.lessons??[];
  const baseWords:Word[]=lessons.flatMap((l:any)=>l.words.map((w:Word)=>({...w,lesson:l})));
  const customWords=buildCustomWords(events,baseWords) as Word[];
  const words:Word[]=[...baseWords,...customWords];
  const currentId=events.filter(e=>e.kind==='setting').at(-1)?.payload.lessonId??1;
  const current=lessons.find((l:any)=>l.id===currentId)??lessons[0];
  const states=new Map(words.map(w=>[w.id,wordState(events,w.id)]));
  const seen=words.filter(w=>states.get(w.id)!.seen),due=words.filter(w=>states.get(w.id)!.due),help=words.filter(w=>states.get(w.id)!.needsHelp);
  const stable=words.filter(w=>states.get(w.id)!.meaning==='较稳固');
  const todayCount=events.filter(e=>['reading','answer'].includes(e.kind)&&new Date(e.at).toDateString()===new Date().toDateString()).length;
  function go(id:string){setPage(id);setMobileMenu(false);setSearch('');window.scrollTo({top:0});}
  function openStudy(w:Word){setStudy(w);setShowPy(false);add('learn',w.id,{source:'card'});}
  function saveCustomWord(){const cleaned=Object.fromEntries(Object.entries(customForm).map(([k,v])=>[k,v.trim()])) as typeof customForm;if(Object.values(cleaned).some(v=>!v)){setNotice('请把字词、拼音、意思和原句都填好。');return;}if(cleaned.term.length>20||Object.values(cleaned).some(v=>v.length>200)){setNotice('内容太长，请把说明写短一些。');return;}if(words.some(w=>w.term===cleaned.term)){setNotice('字词花园已有这个词，可搜索后打开它。');return;}add('customWord','custom-'+crypto.randomUUID(),cleaned);setCustomForm({term:'',pinyin:'',meaning:'',example:''});setAddingWord(false);setFilter('全部');setNotice('已经加入字词花园。刚添的词请先和家长核对释义，再开始练习。');}
  function taskFor(w:Word,q?:Question):Task{return {word:w,question:q,options:q?shuffle(q.options.map((text,index)=>({text,index}))):undefined};}
  function startSession(ws:Word[],title:string,full=false){
    if(!ws.length){setNotice('今天还没有到期的复习字词，可以先学习当前课文。');return;}
    const list:Task[]=[];
    ws.forEach(w=>list.push(taskFor(w)));
    if(full){for(let n=0;n<3;n++)ws.forEach(w=>list.push(taskFor(w,w.questions[n])));}
    else ws.forEach(w=>{const qs=[...w.questions].sort((a,b)=>{const last=(q:Question)=>events.filter(e=>e.wordId===w.id&&e.kind==='answer'&&e.payload.questionId===q.id).at(-1)?.at??0;return last(a)-last(b);});list.push(taskFor(w,qs[0]));});
    setTasks(list);setStep(0);setFeedback(null);setHint(false);setRevealed(false);setConfidence('不确定');setSessionTitle(title);setCompleted(null);results.current=[];setPage('practice');window.scrollTo({top:0});
  }
  function daily(){const currentWords=words.filter(w=>w.lesson.id===current?.id);const chosen=[...due.slice(0,2),...currentWords].filter((w,i,a)=>a.findIndex(x=>x.id===w.id)===i).slice(0,4);startSession(chosen,'今天的小练习');}
  function answer(index:number){if(feedback)return;const task=tasks[step],q=task.question!;const correct=index===q.answer,assisted=hint||wasRecentlyHelped(eventRef.current,task.word.id);add('answer',task.word.id,{questionId:q.id,questionKind:q.kind,correct,assisted,confidence,selected:index});results.current.push({correct,assisted,wordId:task.word.id});setFeedback({correct,assisted,index});add('learn',task.word.id,{source:'feedback'});}
  function readAnswer(ok:boolean){if(feedback)return;const task=tasks[step];add('reading',task.word.id,{ok,selfChecked:true});results.current.push({reading:true,correct:ok,wordId:task.word.id});setFeedback({reading:true,correct:ok});}
  function next(){if(step+1>=tasks.length){setCompleted({count:tasks.length,independent:results.current.filter(r=>!r.reading&&r.correct&&!r.assisted).length,review:new Set(results.current.filter(r=>!r.correct).map(r=>r.wordId)).size});setTasks([]);setPage('complete');sync();}else{setStep(step+1);setFeedback(null);setHint(false);setRevealed(false);setConfidence('不确定');}window.scrollTo({top:0});}
  function exportData(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),events},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='字有意思-学习记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function signOut(){await sync();const response=await fetch('/api/auth/logout',{method:'POST'});if(response.ok)window.location.assign('/login');else setNotice('暂时无法退出，请稍后再试。');}
  function pill(text:string){return <span className={'pill '+(/需要/.test(text)?'warm':/确认|稳固|理解/.test(text)?'green':'')}>{text}</span>;}
  function wordCard(w:Word){const s=states.get(w.id)!;return <button className="word-card" key={w.id} onClick={()=>openStudy(w)}><span className="word-term">{w.term}</span><span className="muted">{w.lesson.id?`第 ${w.lesson.id} 课 · `:''}{w.lesson.title}</span><span className="word-status">{pill(s.reading)}{pill(s.meaning)}</span><span className="card-link">看看这个词 <ArrowRight size={16}/></span></button>;}
  if(dataError)return <main className="loading"><BookOpen/><h1>课本暂时没有打开</h1><p>请检查网络后重试。</p><button onClick={()=>location.reload()}>重新打开</button></main>;
  if(!data||!ready)return <main className="loading"><Sprout size={42}/><h1>字有意思</h1><p>正在打开你的语文小天地…</p></main>;
  const task=tasks[step],q=task?.question;
  return <div className="app-shell"><audio ref={audioRef} preload="none" aria-hidden="true"/>
    <aside className={'sidebar '+(mobileMenu?'open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('home');}}><span className="brand-icon">字</span><span>字有意思<small>每天，读懂一点点</small></span></a><div className="book-label">我的语文小天地</div><nav>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><n.icon size={20}/>{n.title}{n.id==='words'&&help.length>0&&<span className="nav-count">{help.length}</span>}</button>)}</nav><div className="sidebar-note"><Leaf size={26}/><p>慢慢读，认真想。<br/>每一个字，都有意思。</p><span>人教版 · 四年级上册</span></div><button className="sidebar-about" onClick={()=>go('about')}>教材与使用说明 <ChevronRight size={14}/></button></aside>
    <div className="workspace"><header className="topbar"><button className="mobile-toggle icon-btn" aria-label="打开导航" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button><span className="breadcrumb">四年级上册 <ChevronRight size={14}/> {nav.find(n=>n.id===page)?.title??(page==='practice'?'小练习':page==='complete'?'练习完成':'使用说明')}</span><button className="sync-state" onClick={sync} aria-label={'重新同步，'+syncStatus}>{syncStatus.includes('云端')?<Cloud size={16}/>:<CloudOff size={16}/>}<span>{syncStatus}</span></button></header>
      <main className="main-content">
      {page==='home'&&<>
        <div className="eyebrow"><span className="tiny-dot"/> 今天也来认识一点新世界</div>
        <div className="page-heading"><h1>一字一句，慢慢长大<span>。</span></h1><p>读准一个字，也读懂它的意思。</p></div>
        <section className="hero"><div className="hero-copy"><span className="hero-tag">今日学习 · 第{current.id}课</span><h2>{current.title}</h2><p>先试着读一读，再换个情境想一想。<br/>不确定也没关系，我们一起弄明白。</p><button className="primary" onClick={daily}>开始今天的练习 <ArrowRight size={19}/></button><div className="hero-meta">约 8～12 分钟 <span>·</span> 每次最多 4 个字词</div></div><Landscape/></section>
        <div className="stat-strip"><div><span className="stat-icon"><BookOpen size={22}/></span><span><b>{seen.length}<small> / {words.length}</small></b><label>已接触的字词</label></span></div><div><span className="stat-icon ochre"><RefreshCw size={22}/></span><span><b>{due.length}</b><label>到时间复习啦</label></span></div><div><span className="stat-icon pale"><Sprout size={23}/></span><span><b>{stable.length}</b><label>词义记得较稳固</label></span></div></div>
        <div className="section-head"><h2>沿着课本，一步一步</h2><button className="text-btn" onClick={()=>go('book')}>查看全册 <ArrowRight size={16}/></button></div>
        <div className="home-grid"><section className="current-card"><div className="row-between"><span className="muted">第{cn[current.unit-1]}单元 · {unitThemes[current.unit-1]}</span><span className="pill green">正在学习</span></div><h3><span className="lesson-no">{String(current.id).padStart(2,'0')}</span>{current.title}</h3><div className="term-chips">{current.words.map((w:Word)=><button key={w.id} onClick={()=>openStudy({...w,lesson:current})}>{w.term}</button>)}</div><button className="lesson-entry" onClick={()=>{setActiveUnit(current.unit);go('book');}}>走进这一课 <ArrowRight size={18}/></button></section><section className="review-card"><div className="row-between"><span className="mini-icon"><RefreshCw size={23}/></span><span className="pill">温故知新</span></div><h3>{due.length?'老朋友，见面啦':'新认识的字，慢慢记住'}</h3><p>{due.length?`有 ${due.length} 个字词等你再读一读。`:'学过的字词会在之后的日子回来，陪你练得更熟。'}</p><button className="text-btn" onClick={()=>due.length?startSession(due.slice(0,4),'温故知新'):go('words')}>{due.length?'开始复习':'看看字词花园'} <ArrowRight size={16}/></button></section></div>
        <div className="gentle-note"><Lightbulb size={19}/><p>这里不比谁答得快。愿意说“还不清楚”，也是学习的一步。</p><span>今天已练 {todayCount} 题</span></div>
      </>}
      {page==='book'&&<><div className="eyebrow">跟着教材走</div><div className="page-heading"><h1>我的课本<span>。</span></h1><p>选到网课正在学的地方，每一课都可以开始。</p></div><div className="unit-tabs">{cn.map((x,i)=><button key={x} className={activeUnit===i+1?'selected':''} onClick={()=>setActiveUnit(i+1)}>第{x}单元</button>)}</div><div className="section-head"><h2>第{cn[activeUnit-1]}单元 <span className="muted">{unitThemes[activeUnit-1]}</span></h2></div><div className="lesson-list">{lessons.filter((l:any)=>l.unit===activeUnit).map((l:any)=><section className="lesson-row" key={l.id}><div className="lesson-number">{String(l.id).padStart(2,'0')}</div><div className="lesson-detail"><div className="row-title"><h3>{l.title}</h3>{current.id===l.id&&pill('当前课文')}</div><p>{l.words.length} 个精选字词 · 认读与词义分开练</p><div className="term-chips">{l.words.map((w:Word)=><button key={w.id} onClick={()=>openStudy({...w,lesson:l})}>{w.term}</button>)}</div></div><div className="lesson-actions"><button className="primary small" onClick={()=>startSession(words.filter(w=>w.lesson.id===l.id),`第${l.id}课 · ${l.title}`,true)}>开始本课 <ArrowRight size={16}/></button><button className="text-btn" onClick={()=>{add('setting','settings',{lessonId:l.id});setNotice('已设为当前课文，今日学习会跟着这一课走。');}}>设为当前课文</button></div></section>)}</div><p className="footnote">本版先练全册精选字词，不等同于教材全部识字表。<button className="inline-link" onClick={()=>go('about')}>查看教材依据</button></p></>}
      {page==='words'&&<><div className="eyebrow">让每一次相遇都有收获</div><div className="page-heading"><h1>字词花园<span>。</span></h1><p>会读和懂意思，分别记录；不熟悉的词，多见几次。</p></div><button className="secondary add-word-btn" onClick={()=>setAddingWord(true)}>＋ 添加不认识的字词</button><div className="search-box"><Search size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="找一个字、一个词或一篇课文" aria-label="搜索字词"/></div><div className="filter-tabs">{['全部','我的补字','需要巩固','到期复习','我的收藏','已接触'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="word-grid">{words.filter(w=>(w.term.includes(search)||w.lesson.title.includes(search))&&(filter==='全部'||filter==='我的补字'&&w.lesson.id===0||filter==='需要巩固'&&states.get(w.id)!.needsHelp||filter==='到期复习'&&states.get(w.id)!.due||filter==='我的收藏'&&states.get(w.id)!.pinned||filter==='已接触'&&states.get(w.id)!.seen)).map(wordCard)}</div>{!words.some(w=>(w.term.includes(search)||w.lesson.title.includes(search))&&(filter==='全部'||filter==='我的补字'&&w.lesson.id===0||filter==='需要巩固'&&states.get(w.id)!.needsHelp||filter==='到期复习'&&states.get(w.id)!.due||filter==='我的收藏'&&states.get(w.id)!.pinned||filter==='已接触'&&states.get(w.id)!.seen))&&<div className="empty"><Sprout size={38}/><h3>这里还没有字词</h3><p>可以从课本挑选，也可以把刚遇到的字词加进来。</p><button className="primary" onClick={()=>go('book')}>打开课本</button></div>}</>}
      {page==='parent'&&<><div className="eyebrow">把注意力留给真正的盲点</div><div className="page-heading"><h1>看看他的进步<span>。</span></h1><p>题目答对是证据之一，亲口读、举例说，才能了解得更完整。</p></div><div className="parent-controls"><label>网课目前学到 <select value={current.id} onChange={e=>add('setting','settings',{lessonId:Number(e.target.value)})}>{lessons.map((l:any)=><option value={l.id} key={l.id}>{l.id}. {l.title}</option>)}</select></label><button className="secondary" onClick={exportData}><Download size={16}/> 导出学习记录</button></div><div className="stat-strip"><div><span><b>{help.length}</b><label>需要重点巩固</label></span></div><div><span><b>{seen.filter(w=>states.get(w.id)!.reading!=='家长已确认').length}</b><label>已接触 · 待听读确认</label></span></div><div><span><b>{events.filter(e=>e.kind==='answer'&&!e.payload.correct&&e.payload.confidence==='确定').length}</b><label>确信但答错的记录</label></span></div></div><section className="parent-guide"><Lightbulb size={22}/><div><h3>每天抽查两三个词就好</h3><p>请他先读，再用自己的话举一个例子。表达不流利时，可以追问；不要只要求背标准释义。</p></div></section><div className="section-head"><h2>值得一起看看的字词</h2><span className="muted">先显示需要巩固的内容</span></div>{!seen.length?<div className="empty"><BookOpen size={32}/><h3>还没有学习记录</h3><p>完成一次小练习后，这里会展示认读和理解的证据。</p></div>:<div className="parent-table"><div className="table-head"><span>字词 / 课文</span><span>认读情况</span><span>理解情况</span><span>一起确认</span></div>{[...seen].sort((a,b)=>Number(states.get(b.id)!.needsHelp)-Number(states.get(a.id)!.needsHelp)).map(w=>{const s=states.get(w.id)!;return <div className="table-row" key={w.id}><span><b>{w.term}</b><small>{w.lesson.title}</small></span><span>{pill(s.reading)}</span><span>{pill(s.meaning)}<small>{s.contexts} 道不同题有独立答对记录</small></span><button className="text-btn" onClick={()=>{setParentWord(w);setOral('');}}>听读与举例 <ChevronRight size={16}/></button></div>;})}</div>}<section className="evidence-note"><h3>这些状态代表什么？</h3><p>“自行核对过”不是自动语音评分；“初步理解”需要不同题目的独立正确记录；“较稳固”还需要三类题和至少间隔一天的证据。刚看过解释的十分钟内答对，记为练习，不算独立理解。题库有限，家长举例抽查仍有必要。自加字词还需要家长口头确认，才能标为较稳固。</p><p>同一登录账号可跨设备同步。离线时先存本机，联网后合并记录；家长页面是同一账号内的查看入口，未设置独立家长密码。</p></section></>}
      {page==='practice'&&task&&<div className="practice-wrap"><div className="practice-top"><button className="text-btn" onClick={()=>{setTasks([]);go('home');setNotice('已完成的题目已保存，可以稍后继续学习。');}}><ChevronLeft size={17}/> 稍后再练</button><span>{step+1} / {tasks.length}</span></div><div className="progress-track"><div style={{width:`${step/tasks.length*100}%`}}/></div><div className="practice-context">{sessionTitle}</div><section className="question-card"><div className="row-between"><span className="pill green">{!q?'第一步 · 读一读':q.kind==='meaning'?'懂意思':q.kind==='transfer'?'换个情境':'辨一辨'}</span><span className="muted">{task.word.lesson?.title}</span></div>{!q?<><h2 className="read-term">{task.word.term}</h2><p className="center muted">先自己读出来，再打开读音核对。</p>{!revealed?<button className="secondary center-button" onClick={()=>{setRevealed(true);speak(task.word.term);}}><Volume2 size={18}/> 我读好了，听听读音</button>:<><div className="pinyin">{task.word.pinyin} {task.word.term==='降'&&<small>（音频：不肯降）</small>} <button className="icon-btn" aria-label="再听一次" onClick={()=>speak(task.word.term)}><Volume2 size={20}/></button></div><div className="reading-choices"><button disabled={!!feedback} className="answer-option" onClick={()=>readAnswer(true)}>我刚才读对了</button><button disabled={!!feedback} className="answer-option" onClick={()=>readAnswer(false)}>还要练一练</button></div></>}<p className="footnote center">这里记录自己的核对结果，家长听读后再确认。</p></>:<><div className="question-term">{task.word.term}</div><h2 className="question-prompt">{q.prompt}</h2><button className="text-btn" onClick={()=>speak(q.prompt+'。'+task.options!.map((o,i)=>`${i+1}，${o.text}`).join('。'))}><Volume2 size={17}/> 听题目和选项</button><div className="confidence">我现在觉得：{['不确定','确定'].map(c=><button key={c} disabled={!!feedback} className={confidence===c?'selected':''} onClick={()=>setConfidence(c)}>{c}</button>)}</div><div className="answer-options">{task.options!.map((o,i)=><button key={o.index} disabled={!!feedback} className={'answer-option '+(feedback?(o.index===q.answer?'correct':feedback.index===o.index?'wrong':''):'')} onClick={()=>answer(o.index)}><span className="option-number">{cn[i]}</span>{o.text}{feedback&&o.index===q.answer&&<Check size={20}/>}</button>)}</div>{!feedback&&<div className="question-tools"><button className="text-btn" onClick={()=>answer(-1)}>还不清楚</button><button className="text-btn" onClick={()=>setHint(true)}><Eye size={16}/> 看看提示</button></div>}{hint&&<div className="hint-box"><b>{task.word.pinyin}</b><p>{task.word.meaning}</p><small>用了提示也没关系，这次会记为辅助练习。</small></div>}</>}{feedback&&<div className={'feedback '+(feedback.correct?'positive':'retry')} role="status"><h3>{feedback.reading?(feedback.correct?'已记下，之后请家长听一听。':'没关系，下次我们再读一次。'):feedback.correct?(feedback.assisted?'借助提示，练对了！':'这个情境，你理解对了。'):'我们一起把意思弄清楚。'}</h3>{q&&<p>{q.explanation}</p>}<button className="primary" onClick={next}>{step+1===tasks.length?'完成练习':'继续'} <ArrowRight size={18}/></button></div>}</section></div>}
      {page==='complete'&&completed&&<div className="completion"><span className="completion-icon"><Sprout size={54}/></span><div className="eyebrow">今天又多懂了一点</div><h1>认真想过，就是进步。</h1><p>完成了 {completed.count} 道练习。谢谢你没有跳过不确定的地方。</p><div className="completion-stats"><span><b>{completed.independent}</b>道词义题独立答对</span><span><b>{completed.review}</b>个字词值得再见面</span></div><p className="muted">新学会的内容，隔天再试一次。当天练对不等于已经记牢。</p><button className="primary" onClick={()=>go('home')}>回到今日学习 <ArrowRight size={18}/></button><button className="text-btn" onClick={()=>{setFilter('需要巩固');go('words');}}>看看需要巩固的字词</button></div>}
      {page==='about'&&<><div className="page-heading"><h1>关于这本小课本<span>。</span></h1><p>内容范围、使用方法与记录说明。</p></div><section className="about-card"><h2>教材依据</h2><p>{data.edition}</p><p>{data.scopeNote}</p><p>每课精选字词配原创释义、生活例句与三类理解题，不收录整篇课文，不声称覆盖全部会认字、会写字或语文园地。若孩子手中目录不同，请以实际教材为准调整。</p>{data.sources?.map((s:any)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></p>)}<h2>怎样使用</h2><p>家长先设定当前课文。孩子每日练习以少量字词为单位：先读音自查，再判断词义。遇到题库外的不认识字词，可在“字词花园”补充，并请家长核对释义。学习卡中的拼音按需展开；题目可以朗读。</p><h2>发音与评测</h2><p>字词和释义使用预先生成的普通话音频；题目朗读使用设备语音，声音因设备而异。本版不自动识别或评分孩子的录音。遇到多音字，认读以卡片标注的本课词语拼音为准。</p><h2>进度保存</h2><p>指定邮箱登录后，练习记录保存在云端，本机也保留副本。获准的家庭邮箱共用同一份学习进度；网络不可用时会明确显示等待同步。可在家长页面导出备份。</p><button className="secondary" onClick={signOut}>退出登录</button></section></>}
      </main><footer>字有意思 <span>·</span> 让每个字，都成为认识世界的一小步</footer>
    </div>
    {addingWord&&<div className="modal-backdrop" onClick={()=>setAddingWord(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="添加不认识的字词" onClick={e=>e.stopPropagation()}><div className="row-between"><span className="eyebrow">我的补字</span><button className="icon-btn" aria-label="关闭添加字词" onClick={()=>setAddingWord(false)}><X/></button></div><h2>把没认出的字词留下来</h2><p className="muted">请家长和孩子一起核对读音与意思。字词卡和练习会在其他设备同步。</p><div className="custom-form">{([['term','字或词','例如：犹豫'],['pinyin','拼音','例如：yóu yù'],['meaning','这句话里的意思','用简单中文解释'],['example','原句或自己写的句子','请写一个正确使用它的短句']] as const).map(([key,label,placeholder])=><label key={key}>{label}<input value={customForm[key]} maxLength={key==='term'?20:200} placeholder={placeholder} onChange={e=>setCustomForm({...customForm,[key]:e.target.value})}/></label>)}</div><button className="primary full-width" onClick={saveCustomWord}>加入字词花园 <ArrowRight size={18}/></button><p className="footnote">自加字词的理解题由填写的释义和句子生成。要判断是否真正会用，还需家长听他另举一个例子。</p></section></div>}
    {study&&<div className="modal-backdrop" onClick={()=>setStudy(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={'学习'+study.term} onClick={e=>e.stopPropagation()}><div className="row-between"><span className="muted">第{study.lesson?.id}课 · {study.lesson?.title}</span><button className="icon-btn" autoFocus aria-label="关闭学习卡" onClick={()=>setStudy(null)}><X/></button></div><h2 className="study-term">{study.term}</h2><div className="study-tools"><button className="secondary" onClick={()=>speak(study.term)}><Volume2 size={18}/> 听读音</button><button className="secondary" onClick={()=>setShowPy(!showPy)}>{showPy?'收起拼音':'看看拼音'}</button><button className="icon-btn" aria-label="收藏字词" onClick={()=>add('pin',study.id,{on:!states.get(study.id)?.pinned})}><Bookmark fill={states.get(study.id)?.pinned?'currentColor':'none'}/></button></div>{showPy&&<div className="pinyin">{study.pinyin}{study.term==='降'&&<small>（音频：不肯降）</small>}</div>}<div className="meaning-block"><span className="eyebrow">这个词的意思</span><p>{study.meaning}</p><button className="text-btn" onClick={()=>speak(study.meaning)}><Volume2 size={16}/> 听解释</button></div><div className="example-block"><b>放进生活里</b><p>{study.example}</p></div>{study.confusion&&<p className="confusion"><Lightbulb size={18}/>{study.confusion}</p>}<div className="oral-prompt"><b>自己说一说</b><p>{study.oralPrompt}</p></div><button className="primary full-width" onClick={()=>{const w=study;setStudy(null);startSession([w],'学过之后，试一试',true);}}>来练一练 <ArrowRight size={18}/></button><p className="footnote center">刚看过解释的答题记为练习，之后再检测独立理解。</p></section></div>}
    {parentWord&&<div className="modal-backdrop" onClick={()=>setParentWord(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="家长确认" onClick={e=>e.stopPropagation()}><div className="row-between"><span className="eyebrow">一起确认 · {parentWord.term}</span><button className="icon-btn" autoFocus aria-label="关闭家长确认" onClick={()=>setParentWord(null)}><X/></button></div><h2>先听读，再听他举例</h2><p>请先让孩子看着“{parentWord.term}”读出来。</p><details><summary>家长查看读音与释义</summary><p>{parentWord.pinyin} · {parentWord.meaning}</p></details><div className="reading-choices"><button className="secondary" onClick={()=>{add('parentRead',parentWord.id,{ok:true});setNotice('认读已由家长确认。');}}>听读正确</button><button className="secondary" onClick={()=>{add('parentRead',parentWord.id,{ok:false});setNotice('已标记需要练读。');}}>还需要练读</button></div><div className="oral-prompt"><b>接着问一问</b><p>{parentWord.oralPrompt}</p></div><label className="oral-label">记下他的表达（选填）<textarea maxLength={500} value={oral} onChange={e=>setOral(e.target.value)} placeholder="意思说对了就可以，不要求背标准解释。"/></label><div className="reading-choices"><button className="primary small" onClick={()=>{add('parentMeaning',parentWord.id,{ok:true,note:oral});setParentWord(null);setNotice('已记录：口头表达经家长确认。');}}>能举出合理例子</button><button className="secondary" onClick={()=>{add('parentMeaning',parentWord.id,{ok:false,note:oral});setParentWord(null);}}>还需要帮助</button></div><h3>最近的理解记录</h3><div className="history-list">{events.filter(e=>e.wordId===parentWord.id&&['answer','parentMeaning'].includes(e.kind)).slice(-5).reverse().map(e=><p key={e.id}>{dateLabel(e.at)} · {e.kind==='parentMeaning'?`家长确认：${e.payload.ok?'表达合理':'需要帮助'}${e.payload.note?' · '+e.payload.note:''}`:`${e.payload.correct?'答对':'需要巩固'} · ${e.payload.assisted?'看过提示':'独立作答'} · ${e.payload.confidence}`}</p>)}</div></section></div>}
    {notice&&<div className="toast" role="status">{notice}</div>}
  </div>;
}


